#!/bin/bash

running_dir=$(cd $(dirname "$0") && pwd)
node_version="$1"
[ -z "${node_version}" ] && node_version="10.3.0"

echo "

# install node
nvm use v${node_version} || nvm install v${node_version}

# set terminal alias
alias roxterm='roxterm -c Default -d \${HOME}'

" > /tmp/docker_init_script
chmod +x /tmp/docker_init_script

docker-compose up -d ubuntu-desktop-develop

echo "STARTING......"
sleep 3



echo "VIEWING......"
/Applications/VNC\ Viewer.app/Contents/MacOS/vncviewer localhost:15901 -passwd "${running_dir}/ubuntu-desktop-develop/passwd"



echo "STOPING......"
docker-compose down
