#!/bin/bash

running_dir=$(cd $(dirname "$0") && pwd)
node_version="$1"
[ -z "${node_version}" ] && node_version="10.3.0"

echo "

# install node
nvm use v${node_version} || nvm install v${node_version}

# set terminal alias
alias roxterm='roxterm -c Default -d \${HOME}'

" > /tmp/docker_init_script
chmod +x /tmp/docker_init_script



docker run --name ubuntu-desktop-develop --rm \
  -p 1022:22 \
  -p 5901:5901 \
  -p 5000:5000/tcp \
  -w "/home/${USER}" \
  -v "/tmp/docker_init_script:/tmp/docker_init_script" \
  -v "${HOME}/develop_home:/home/${USER}" \
  -v "${HOME}:/home/${USER}/host_home" \
  -v ${HOME}/.ssh:/home/${USER}/.ssh \
  -v ${HOME}/.gitconfig:/home/${USER}/.gitconfig \
  garywu/ubuntu-desktop-develop &

echo "STARTING......"
sleep 3



echo "VIEWING......"
/Applications/VNC\ Viewer.app/Contents/MacOS/vncviewer localhost:1 -passwd "${running_dir}/ubuntu-desktop-develop/passwd"



echo "STOPING......"
docker stop ubuntu-desktop-develop
